<?php

return [
    'accepted' => \Kontrolio\Rules\Core\Accepted::class,
    'alpha' => \Kontrolio\Rules\Core\Alpha::class,
    'alphadash' => \Kontrolio\Rules\Core\Alphadash::class,
    'alphanum' => \Kontrolio\Rules\Core\Alphanum::class,
    'blank' => \Kontrolio\Rules\Core\Blank::class,
    'card_scheme' => \Kontrolio\Rules\Core\CardScheme::class,
    'date' => \Kontrolio\Rules\Core\Date::class,
    'date_time' => \Kontrolio\Rules\Core\DateTime::class,
    'email' => \Kontrolio\Rules\Core\Email::class,
    'each_passed' => \Kontrolio\Rules\Core\EachPassed::class,
    'equal_to' => \Kontrolio\Rules\Core\EqualTo::class,
    'first_passed' => \Kontrolio\Rules\Core\FirstPassed::class,
    'greater_than' => \Kontrolio\Rules\Core\GreaterThan::class,
    'greater_than_or_equal' => \Kontrolio\Rules\Core\GreaterThanOrEqual::class,
    'identical_to' => \Kontrolio\Rules\Core\IdenticalTo::class,
    'inn' => \Kontrolio\Rules\Core\Inn::class,
    'ip' => \Kontrolio\Rules\Core\Ip::class,
    'is_false' => \Kontrolio\Rules\Core\IsFalse::class,
    'is_null' => \Kontrolio\Rules\Core\IsNull::class,
    'is_true' => \Kontrolio\Rules\Core\IsTrue::class,
    'kpp' => \Kontrolio\Rules\Core\Kpp::class,
    'length' => \Kontrolio\Rules\Core\Length::class,
    'less_than' => \Kontrolio\Rules\Core\LessThan::class,
    'less_than_or_equal' => \Kontrolio\Rules\Core\LessThanOrEqual::class,
    'not_blank' => \Kontrolio\Rules\Core\NotBlank::class,
    'not_equal_to' => \Kontrolio\Rules\Core\NotEqualTo::class,
    'not_identical_to' => \Kontrolio\Rules\Core\NotIdenticalTo::class,
    'not_null' => \Kontrolio\Rules\Core\NotNull::class,
    'ogrn' => \Kontrolio\Rules\Core\Ogrn::class,
    'okpo' => \Kontrolio\Rules\Core\Okpo::class,
    'range' => \Kontrolio\Rules\Core\Range::class,
    'is_in' => \Kontrolio\Rules\Core\IsIn::class,
    'snils' => \Kontrolio\Rules\Core\Snils::class,
    'sometimes' => \Kontrolio\Rules\Core\Sometimes::class,
    'time' => \Kontrolio\Rules\Core\Time::class,
    'until_first_failure' => \Kontrolio\Rules\Core\UntilFirstFailure::class,
    'url' => \Kontrolio\Rules\Core\Url::class
];
