name: 'Continuous Integration'

on:
  pull_request: ~
  push: ~

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
        with:
          configuration: ./phpunit.xml.dist
          php_extensions: ctype mbstring
